version: '3'

services:
  # PostgreSQL
  postgres:
    image: sushantdhiman/postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NeelpsAnanab69
      POSTGRES_DB: la_croisee_des_terroirs
    volumes:
      - /mnt/sequelize-postgres-ramdisk:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    container_name: postgres

  lcdt_back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lcdt_back
    ports:
      - "3000:3000"
    networks:
      - postgres
    environment:
      NODE_ENV: dev
    volumes:
      - ./src/:/usr/src/app/:rw

networks:
  postgres: null