version: '2'

services:
  sequelize:
    build: .
    links:
     - postgres-95
    volumes:
      - .:/sequelize
    environment:
      SEQ_DB: la_croisee_des_terroirs
      SEQ_USER: postgres
      SEQ_PW: NeelpsAnanab69

  # PostgreSQL
  postgres-95:
    image: sushantdhiman/postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NeelpsAnanab69
      POSTGRES_DB: la_croisee_des_terroirs
    volumes:
      - /mnt/sequelize-postgres-ramdisk:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres-95

  lcdt_back:
    build: .
    container_name: lcdt_back
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
    volumes:
      - ./src/:/usr/src/app/:rw